fix: handle errors from map rendering more gracefully (#649)
Fixes an issue that I've noticed happening more recently in CI ([Sentry
event](https://awana-digital.sentry.io/issues/7652533399/)):

> GPUInitializationError: WebGL2 is required to display this map. We are
sorry, but it seems that your browser does not support WebGL2, a
technology for rendering 3D graphics on the web. Read more on
https://wiki.openstreetmap.org/wiki/This_map_requires_WebGL

This is directly related to upgrading maplibre-gl to v6 in #644 , which
now only supports WebGL2. From what I can tell, we shouldn't really be
having issues with WebGL2 support on the actions runners we use (nor the
Chrome version that Electron uses), so not sure why the error is coming
up in those scenarios. Regardless, we should be handling map rendering
errors more gracefully. In this case, the solution should prevent the
e2e tests from failing in CI when the map error occurs, as the UI that's
being tested will remain in place.

---

- Before

<img width="600" alt="image"
src="https://github.com/user-attachments/assets/57873a7c-f106-44db-97e8-311162a4942c"
/>

- After

<img width="600" alt="image"
src="https://github.com/user-attachments/assets/4bb14b3e-e17a-4efc-abf9-ed5e3bf1f7f2"
/>